# Generated by Django 4.1.5 on 2023-01-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pierogi',
            name='verified_artist',
        ),
    ]
